### ISSUE TITLE
Add support update_password = on_create

### ISSUE THREAD

**Issue by jnerin** [philsch/ansible-redshift#3] opened 2018-04-11 14:31 UTC
Hello,

As a way to workaround or solve the issue about always reporting a changed status, perhaps you could add a new setting as in the mysql_user module that allows you to skip setting the password if the user already exists on the server, see http://docs.ansible.com/ansible/latest/modules/mysql_user_module.html 

update_password | Choices: always ← on_create | always will update passwords if they differ. on_create will only set the password for newly created users.

We create users on mysql servers by generating a random password, sending it securely to the user, setting it on the db with this code:

`update_password=on_create password="{{lookup('file', 'mysql_credentials/' + item.key )}}"`

And overwriting the file with a different random value so that ansible is happy that the file exists and has a value (although is not using it anymore for existing users). This way we don't have a place with all the users' passwords stored in plain text.

Kind regards.

**Comment by philsch** [comment] 2018-04-13 06:49
Hi @jnerin 

Thanks for your suggestion and providing an example why it is useful. The `update_password` flag is available now in the *develop* branch of this repository. If you like you can test the code in your project and give me feedback if it's working as intended, I'll create a release to *master* later.

If `update_password=on_create` and you don't use the `privs` feature of this module, the Ansible *changed*-flag is now set correctly depending if a user / group is modified.

Best,
Philipp

**Comment by philsch** [comment] 2018-04-16 16:37
Released in **0.2.0**

**Closed by philsch** 2018-04-16 16:37 UTC
Labels: enhancement, released
